-- /mnt/docs/src/noted/test/assets/koreader/pg42324.sdr/metadata.epub.lua
return {
    ["annotations"] = {
        [1] = {
            ["chapter"] = "Titlepage",
            ["datetime"] = "2023-12-22 18:17:37",
            ["page"] = "/body/DocFragment[2]/body/p/img.0",
            ["pageno"] = 2,
            ["text"] = "in Titlepage",
        },
        [2] = {
            ["chapter"] = "Chapter XXIII",
            ["color"] = "yellow",
            ["datetime"] = "2023-12-23 08:47:28",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[35]/body/p[15]/text().330",
            ["pageno"] = 265,
            ["pos0"] = "/body/DocFragment[35]/body/p[15]/text().330",
            ["pos1"] = "/body/DocFragment[35]/body/p[15]/text().451",
            ["text"] = "But the overflowing misery I now felt, and the excess of agitation that I endured, rendered me incapable of any exertion.",
        },
        [3] = {
            ["chapter"] = "Chapter XXIII",
            ["color"] = "yellow",
            ["datetime"] = "2023-12-19 17:23:52",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[35]/body/p[15]/text().925",
            ["pageno"] = 265,
            ["pos0"] = "/body/DocFragment[35]/body/p[15]/text().925",
            ["pos1"] = "/body/DocFragment[35]/body/p[15]/text().994",
            ["text"] = "Nothing is so painful to the human mind as a great and sudden change.",
        },
        [4] = {
            ["chapter"] = "Chapter XXIII",
            ["color"] = "yellow",
            ["datetime"] = "2023-12-19 17:24:26",
            ["drawer"] = "lighten",
            ["note"] = "Sample note without highlight",
            ["page"] = "/body/DocFragment[35]/body/p[15]/text().995",
            ["pageno"] = 265,
            ["pos0"] = "/body/DocFragment[35]/body/p[15]/text().995",
            ["pos1"] = "/body/DocFragment[35]/body/p[15]/text().1104",
            ["text"] = "The sun might shine, or the clouds might lower: but nothing could appear to me as it had done the day before.",
        },
        [5] = {
            ["chapter"] = "Walton, in Continuation",
            ["color"] = "yellow",
            ["datetime"] = "2023-12-22 18:17:17",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[36]/body/p[30]/text().0",
            ["pageno"] = 281,
            ["pos0"] = "/body/DocFragment[36]/body/p[30]/text().0",
            ["pos1"] = "/body/DocFragment[36]/body/p[30]/text().56",
            ["text"] = "You have read this strange and terrific story, Margaret;",
        },
    },
    ["bookmarks"] = {
        [1] = {
            ["chapter"] = "Walton, in Continuation",
            ["datetime"] = "2023-12-22 18:17:17",
            ["highlighted"] = true,
            ["notes"] = "You have read this strange and terrific story, Margaret;",
            ["page"] = "/body/DocFragment[36]/body/p[30]/text().0",
            ["pos0"] = "/body/DocFragment[36]/body/p[30]/text().0",
            ["pos1"] = "/body/DocFragment[36]/body/p[30]/text().56",
            ["text"] = "Page 281 You have read this strange and terrific story, Margaret; @ 2023-12-22 18:17:17",
        },
        [2] = {
            ["chapter"] = "Chapter XXIII",
            ["datetime"] = "2023-12-19 17:24:26",
            ["highlighted"] = true,
            ["notes"] = "The sun might shine, or the clouds might lower: but nothing could appear to me as it had done the day before.",
            ["page"] = "/body/DocFragment[35]/body/p[15]/text().995",
            ["pos0"] = "/body/DocFragment[35]/body/p[15]/text().995",
            ["pos1"] = "/body/DocFragment[35]/body/p[15]/text().1104",
            ["text"] = "Sample note without highlight",
        },
        [3] = {
            ["chapter"] = "Chapter XXIII",
            ["datetime"] = "2023-12-19 17:23:52",
            ["highlighted"] = true,
            ["notes"] = "Nothing is so painful to the human mind as a great and sudden change.",
            ["page"] = "/body/DocFragment[35]/body/p[15]/text().925",
            ["pos0"] = "/body/DocFragment[35]/body/p[15]/text().925",
            ["pos1"] = "/body/DocFragment[35]/body/p[15]/text().994",
            ["text"] = "Page 265 Nothing is so painful to the human mind as a great and sudden change. @ 2023-12-19 17:23:52",
        },
        [4] = {
            ["chapter"] = "Chapter XXIII",
            ["datetime"] = "2023-12-23 08:47:28",
            ["highlighted"] = true,
            ["notes"] = "But the overflowing misery I now felt, and the excess of agitation that I endured, rendered me incapable of any exertion.",
            ["page"] = "/body/DocFragment[35]/body/p[15]/text().330",
            ["pos0"] = "/body/DocFragment[35]/body/p[15]/text().330",
            ["pos1"] = "/body/DocFragment[35]/body/p[15]/text().451",
        },
        [5] = {
            ["chapter"] = "Titlepage",
            ["datetime"] = "2023-12-22 18:17:37",
            ["notes"] = "in Titlepage",
            ["page"] = "/body/DocFragment[2]/body/p/img.0",
            ["text"] = "Page 2 in Titlepage @ 2023-12-22 18:17:37",
        },
    },
    ["bookmarks_sorted_20220106"] = true,
    ["bookmarks_version"] = 20200615,
    ["cache_file_path"] = "/home/arun/.config/koreader/cache/cr3cache/pg42324.epub.3a30c574.1.cr3",
    ["config_panel_index"] = 1,
    ["copt_b_page_margin"] = 15,
    ["copt_block_rendering_mode"] = 3,
    ["copt_cjk_width_scaling"] = 100,
    ["copt_embedded_css"] = 1,
    ["copt_embedded_fonts"] = 1,
    ["copt_font_base_weight"] = 0,
    ["copt_font_gamma"] = 15,
    ["copt_font_hinting"] = 2,
    ["copt_font_kerning"] = 3,
    ["copt_font_size"] = 22,
    ["copt_h_page_margins"] = {
        [1] = 10,
        [2] = 10,
    },
    ["copt_line_spacing"] = 100,
    ["copt_nightmode_images"] = 1,
    ["copt_render_dpi"] = 96,
    ["copt_rotation_mode"] = 0,
    ["copt_smooth_scaling"] = 0,
    ["copt_status_line"] = 1,
    ["copt_sync_t_b_page_margins"] = 0,
    ["copt_t_page_margin"] = 15,
    ["copt_view_mode"] = 0,
    ["copt_visible_pages"] = 1,
    ["copt_word_expansion"] = 0,
    ["copt_word_spacing"] = {
        [1] = 95,
        [2] = 75,
    },
    ["cre_dom_version"] = 20210904,
    ["css"] = "./data/epub.css",
    ["doc_pages"] = 310,
    ["doc_path"] = "/mnt/docs/src/noted/test/assets/koreader/pg42324.epub",
    ["doc_props"] = {
        ["authors"] = "Mary Shelley",
        ["description"] = "A tragic scientist creates a monster in his laboratory.",
        ["identifiers"] = "MOBI-ASIN:251f3dca-e069-4593-9299-2752b188021d\
uuid:ea0e9e43-816a-41d0-aecb-d4b3778d5e79",
        ["keywords"] = "Science fiction\
Horror tales\
Gothic fiction (Literary genre)\
Scientists -- Fiction\
Monsters -- Fiction\
Frankenstein\
Victor (Fictitious character) -- Fiction\
Frankenstein's monster (Fictitious character) -- Fiction",
        ["language"] = "en",
        ["title"] = "Frankenstein",
    },
    ["floating_punctuation"] = 0,
    ["font_face"] = "Noto Serif",
    ["font_family_fonts"] = {},
    ["handmade_flows_edit_enabled"] = true,
    ["handmade_flows_enabled"] = false,
    ["handmade_toc_edit_enabled"] = true,
    ["handmade_toc_enabled"] = false,
    ["header_font_face"] = "Noto Sans",
    ["hide_nonlinear_flows"] = false,
    ["highlight"] = {
        [261] = {
            [1] = {
                ["chapter"] = "Chapter XXIII",
                ["datetime"] = "2023-12-19 17:23:52",
                ["drawer"] = "lighten",
                ["pos0"] = "/body/DocFragment[35]/body/p[15]/text().925",
                ["pos1"] = "/body/DocFragment[35]/body/p[15]/text().994",
                ["text"] = "Nothing is so painful to the human mind as a great and sudden change.",
            },
            [2] = {
                ["chapter"] = "Chapter XXIII",
                ["datetime"] = "2023-12-19 17:24:26",
                ["drawer"] = "lighten",
                ["pos0"] = "/body/DocFragment[35]/body/p[15]/text().995",
                ["pos1"] = "/body/DocFragment[35]/body/p[15]/text().1104",
                ["text"] = "The sun might shine, or the clouds might lower: but nothing could appear to me as it had done the day before.",
            },
        },
        [265] = {
            [1] = {
                ["chapter"] = "Chapter XXIII",
                ["datetime"] = "2023-12-23 08:47:28",
                ["drawer"] = "lighten",
                ["pos0"] = "/body/DocFragment[35]/body/p[15]/text().330",
                ["pos1"] = "/body/DocFragment[35]/body/p[15]/text().451",
                ["text"] = "But the overflowing misery I now felt, and the excess of agitation that I endured, rendered me incapable of any exertion.",
            },
        },
        [281] = {
            [1] = {
                ["chapter"] = "Walton, in Continuation",
                ["datetime"] = "2023-12-22 18:17:17",
                ["drawer"] = "lighten",
                ["pos0"] = "/body/DocFragment[36]/body/p[30]/text().0",
                ["pos1"] = "/body/DocFragment[36]/body/p[30]/text().56",
                ["text"] = "You have read this strange and terrific story, Margaret;",
            },
        },
    },
    ["highlight_color"] = "yellow",
    ["highlight_drawer"] = "lighten",
    ["highlights_imported"] = true,
    ["hyph_force_algorithmic"] = false,
    ["hyph_soft_hyphens_only"] = false,
    ["hyph_trust_soft_hyphens"] = false,
    ["hyphenation"] = true,
    ["inverse_reading_order"] = false,
    ["last_xpointer"] = "/body/DocFragment[35]/body/p[16]/text().0",
    ["page_overlap_style"] = "dim",
    ["partial_md5_checksum"] = "9336eb2f430a0d0e71dd0882eb74d27c",
    ["partial_rerendering"] = true,
    ["percent_finished"] = 0.85806451612903,
    ["preferred_dictionaries"] = {},
    ["readermenu_tab_index"] = 1,
    ["show_overlap_enable"] = false,
    ["stats"] = {
        ["authors"] = "Mary Shelley",
        ["highlights"] = 3,
        ["language"] = "en",
        ["notes"] = 1,
        ["pages"] = 310,
        ["performance_in_pages"] = {},
        ["series"] = "N/A",
        ["title"] = "Frankenstein",
    },
    ["summary"] = {
        ["modified"] = "2023-12-19",
        ["status"] = "reading",
    },
    ["text_lang"] = "en-US",
    ["text_lang_embedded_langs"] = true,
    ["toc_ticks_ignored_levels"] = {},
}
