-- /mnt/docs/src/noted/test/assets/koreader/dialogues_seneca.sdr/metadata.epub.lua
return {
    ["annotations"] = {},
    ["cache_file_path"] = "/home/arun/.config/koreader/cache/cr3cache/dialogues_seneca.epub.43cde243.1.cr3",
    ["config_panel_index"] = 1,
    ["copt_b_page_margin"] = 15,
    ["copt_block_rendering_mode"] = 3,
    ["copt_cjk_width_scaling"] = 100,
    ["copt_embedded_css"] = 1,
    ["copt_embedded_fonts"] = 1,
    ["copt_font_base_weight"] = 0,
    ["copt_font_gamma"] = 15,
    ["copt_font_hinting"] = 2,
    ["copt_font_kerning"] = 3,
    ["copt_font_size"] = 22,
    ["copt_h_page_margins"] = {
        [1] = 10,
        [2] = 10,
    },
    ["copt_line_spacing"] = 100,
    ["copt_nightmode_images"] = 1,
    ["copt_render_dpi"] = 96,
    ["copt_rotation_mode"] = 0,
    ["copt_smooth_scaling"] = 0,
    ["copt_status_line"] = 1,
    ["copt_sync_t_b_page_margins"] = 0,
    ["copt_t_page_margin"] = 15,
    ["copt_view_mode"] = 0,
    ["copt_visible_pages"] = 1,
    ["copt_word_expansion"] = 0,
    ["copt_word_spacing"] = {
        [1] = 95,
        [2] = 75,
    },
    ["cre_dom_version"] = 20240114,
    ["css"] = "./data/epub.css",
    ["doc_pages"] = 972,
    ["doc_path"] = "/mnt/docs/src/noted/test/assets/koreader/dialogues_seneca.epub",
    ["doc_props"] = {
        ["authors"] = "Seneca",
        ["description"] = "Seneca’s dialogues and consolations, including “On Benefits,” examine living life through the lens of Stoic philosophy.",
        ["identifiers"] = "url:https://standardebooks.org/ebooks/seneca/dialogues/aubrey-stewart\
calibre:540\
uuid:5d68b78a-d32e-49bd-bc10-faf5f1bc9102\
url:https://standardebooks.org/ebooks/seneca/dialogues/aubrey-stewart",
        ["keywords"] = "Classical literature\
Essays\
Conduct of life\
Benevolence",
        ["language"] = "en-GB",
        ["title"] = "Dialogues",
    },
    ["floating_punctuation"] = 0,
    ["font_face"] = "Noto Serif",
    ["font_family_fonts"] = {},
    ["handmade_flows_edit_enabled"] = true,
    ["handmade_flows_enabled"] = false,
    ["handmade_toc_edit_enabled"] = true,
    ["handmade_toc_enabled"] = false,
    ["hide_nonlinear_flows"] = false,
    ["highlight_color"] = "yellow",
    ["highlight_drawer"] = "lighten",
    ["hyph_force_algorithmic"] = false,
    ["hyph_soft_hyphens_only"] = false,
    ["hyph_trust_soft_hyphens"] = false,
    ["hyphenation"] = true,
    ["inverse_reading_order"] = false,
    ["last_xpointer"] = "/body/DocFragment[1]/body/section/h1/text().0",
    ["page_overlap_style"] = "dim",
    ["partial_md5_checksum"] = "02d007c77416879977dce44c4dc3c2ac",
    ["partial_rerendering"] = true,
    ["percent_finished"] = 0.0010288065843621,
    ["preferred_dictionaries"] = {},
    ["readermenu_tab_index"] = 1,
    ["show_overlap_enable"] = false,
    ["stats"] = {
        ["authors"] = "Seneca",
        ["highlights"] = 0,
        ["language"] = "en-GB",
        ["notes"] = 0,
        ["pages"] = 972,
        ["performance_in_pages"] = {},
        ["series"] = "N/A",
        ["title"] = "Dialogues",
    },
    ["summary"] = {
        ["modified"] = "2024-12-25",
        ["status"] = "reading",
    },
    ["text_lang"] = "en-GB",
    ["text_lang_embedded_langs"] = true,
    ["toc_ticks_ignored_levels"] = {},
}
