name: Build

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Install .NET (v6.0)
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.x
      - name: Test
        run: |
          dotnet test --configuration Debug
          dotnet test --configuration Release
      - name: Publish
        run: dotnet publish src/Noted -o src/Noted/bin/Publish/ --configuration Release
      - name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Noted.${{ matrix.os }}
          path: src/Noted/bin/Publish/

  publish:
    if: contains(github.ref, 'tags/v') # only publish tagged versions
    needs: [test]
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - uses: actions/checkout@v1
      - name: Install .NET (v6.0)
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.x
      - name: Extract version
        id: extract_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
        shell: bash
      - name: Build
        run: |
          dotnet publish src/Noted -c Release --self-contained false -r win-x64 -o ./src/Noted/bin/Portable.win-x64
          dotnet publish src/Noted -c Release --self-contained false -r linux-x64 -o ./src/Noted/bin/Portable.linux-x64
          dotnet publish src/Noted -c Release --self-contained -r win-x64 -o ./src/Noted/bin/win-x64
          dotnet publish src/Noted -c Release --self-contained -r linux-x64 -o ./src/Noted/bin/linux-x64
          7z a src/Noted/bin/Noted.${{ steps.extract_version.outputs.version }}.Portable.win-x64.zip ./src/Noted/bin/Portable.win-x64 -r
          7z a src/Noted/bin/Noted.${{ steps.extract_version.outputs.version }}.Portable.linux-x64.zip ./src/Noted/bin/Portable.linux-x64 -r
          7z a src/Noted/bin/Noted.${{ steps.extract_version.outputs.version }}.win-x64.zip ./src/Noted/bin/win-x64 -r
          7z a src/Noted/bin/Noted.${{ steps.extract_version.outputs.version }}.linux-x64.zip ./src/Noted/bin/linux-x64 -r
          ls -l src/Noted/bin
      - name: Create Release
        uses: ncipollo/release-action@v1.9.0
        with:
          name: Release ${{ steps.extract_version.outputs.version }}
          body: |
              [Changelog](https://github.com/codito/Noted/blob/master/CHANGELOG.md)
          artifacts: "src/Noted/bin/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
