-- /home/arun/src/noted/test/assets/koreader/the_prophet.sdr/metadata.epub.lua
return {
    ["bookmarks"] = {
        [1] = {
            ["chapter"] = "On Giving",
            ["datetime"] = "2023-12-20 21:02:40",
            ["highlighted"] = true,
            ["notes"] = "You give but little when you give of your possessions.\
It is when you give of yourself that you truly give.",
            ["page"] = "/body/DocFragment[9]/body/article/p[3]/text().0",
            ["pos0"] = "/body/DocFragment[9]/body/article/p[3]/text().0",
            ["pos1"] = "/body/DocFragment[9]/body/article/p[4]/text().52",
        },
        [2] = {
            ["chapter"] = "On Marriage",
            ["datetime"] = "2023-12-20 21:02:16",
            ["notes"] = "in On Marriage",
            ["page"] = "/body/DocFragment[7]/body/article/p[10]/text().0",
        },
        [3] = {
            ["chapter"] = "On Love",
            ["datetime"] = "2023-12-20 21:01:06",
            ["highlighted"] = true,
            ["notes"] = "Love gives naught but itself and takes naught but from itself.\
Love possesses not nor would it be possessed;\
For love is sufficient unto love.",
            ["page"] = "/body/DocFragment[6]/body/article/p[22]/text().0",
            ["pos0"] = "/body/DocFragment[6]/body/article/p[22]/text().0",
            ["pos1"] = "/body/DocFragment[6]/body/article/p[24]/text().33",
            ["text"] = "Sample note",
        },
        [4] = {
            ["chapter"] = "The Coming of the Ship",
            ["datetime"] = "2023-12-20 20:59:31",
            ["highlighted"] = true,
            ["notes"] = "And then shall I come to you, a boundless drop to a boundless ocean.",
            ["page"] = "/body/DocFragment[5]/body/article/p[24]/text().0",
            ["pos0"] = "/body/DocFragment[5]/body/article/p[24]/text().0",
            ["pos1"] = "/body/DocFragment[5]/body/article/p[24]/text().68",
            ["text"] = "Page 7 And then shall I come to you, a boundless drop to a boundless ocean. @ 2023-12-20 20:59:31",
        },
    },
    ["bookmarks_sorted_20220106"] = true,
    ["bookmarks_version"] = 20200615,
    ["cache_file_path"] = "/home/arun/.config/koreader/cache/cr3cache/the_prophet.epub.31deabf0.1.cr3",
    ["config_panel_index"] = 1,
    ["copt_b_page_margin"] = 15,
    ["copt_block_rendering_mode"] = 3,
    ["copt_cjk_width_scaling"] = 100,
    ["copt_embedded_css"] = 1,
    ["copt_embedded_fonts"] = 1,
    ["copt_font_base_weight"] = 0,
    ["copt_font_gamma"] = 15,
    ["copt_font_hinting"] = 2,
    ["copt_font_kerning"] = 3,
    ["copt_font_size"] = 22,
    ["copt_h_page_margins"] = {
        [1] = 10,
        [2] = 10,
    },
    ["copt_line_spacing"] = 100,
    ["copt_nightmode_images"] = 1,
    ["copt_render_dpi"] = 96,
    ["copt_rotation_mode"] = 0,
    ["copt_smooth_scaling"] = 0,
    ["copt_status_line"] = 1,
    ["copt_sync_t_b_page_margins"] = 0,
    ["copt_t_page_margin"] = 15,
    ["copt_view_mode"] = 0,
    ["copt_visible_pages"] = 1,
    ["copt_word_expansion"] = 0,
    ["copt_word_spacing"] = {
        [1] = 95,
        [2] = 75,
    },
    ["cre_dom_version"] = 20210904,
    ["css"] = "./data/epub.css",
    ["doc_pages"] = 103,
    ["doc_path"] = "/home/arun/src/noted/test/assets/koreader/the_prophet.epub",
    ["doc_props"] = {
        ["authors"] = "Khalil Gibran",
        ["description"] = "A collection of prose poetry on themes such as love, beauty, and religion.",
        ["keywords"] = "Mysticism⁠-Poetry\
Prose poems, American",
        ["language"] = "en-US",
        ["title"] = "The Prophet",
    },
    ["floating_punctuation"] = 0,
    ["font_face"] = "Noto Serif",
    ["font_family_fonts"] = {},
    ["handmade_flows_edit_enabled"] = true,
    ["handmade_flows_enabled"] = false,
    ["handmade_toc_edit_enabled"] = true,
    ["handmade_toc_enabled"] = false,
    ["header_font_face"] = "Noto Sans",
    ["hide_nonlinear_flows"] = false,
    ["highlight"] = {
        [7] = {
            [1] = {
                ["chapter"] = "The Coming of the Ship",
                ["datetime"] = "2023-12-20 20:59:31",
                ["drawer"] = "lighten",
                ["pos0"] = "/body/DocFragment[5]/body/article/p[24]/text().0",
                ["pos1"] = "/body/DocFragment[5]/body/article/p[24]/text().68",
                ["text"] = "And then shall I come to you, a boundless drop to a boundless ocean.",
            },
        },
        [14] = {
            [1] = {
                ["chapter"] = "On Love",
                ["datetime"] = "2023-12-20 21:01:06",
                ["drawer"] = "lighten",
                ["pos0"] = "/body/DocFragment[6]/body/article/p[22]/text().0",
                ["pos1"] = "/body/DocFragment[6]/body/article/p[24]/text().33",
                ["text"] = "Love gives naught but itself and takes naught but from itself.\
Love possesses not nor would it be possessed;\
For love is sufficient unto love.",
            },
        },
        [20] = {
            [1] = {
                ["chapter"] = "On Giving",
                ["datetime"] = "2023-12-20 21:02:40",
                ["drawer"] = "lighten",
                ["pos0"] = "/body/DocFragment[9]/body/article/p[3]/text().0",
                ["pos1"] = "/body/DocFragment[9]/body/article/p[4]/text().52",
                ["text"] = "You give but little when you give of your possessions.\
It is when you give of yourself that you truly give.",
            },
        },
    },
    ["highlight_drawer"] = "lighten",
    ["highlights_imported"] = true,
    ["hyph_force_algorithmic"] = false,
    ["hyph_soft_hyphens_only"] = false,
    ["hyph_trust_soft_hyphens"] = false,
    ["hyphenation"] = true,
    ["inverse_reading_order"] = false,
    ["last_xpointer"] = "/body/DocFragment[9]/body/article/p[1]/text().0",
    ["page_overlap_style"] = "dim",
    ["partial_md5_checksum"] = "2107aa7e6601b1c5459134e763c87d5b",
    ["partial_rerendering"] = true,
    ["percent_finished"] = 0.19417475728155,
    ["preferred_dictionaries"] = {},
    ["readermenu_tab_index"] = 3,
    ["show_overlap_enable"] = false,
    ["stats"] = {
        ["authors"] = "Khalil Gibran",
        ["highlights"] = 2,
        ["language"] = "en-US",
        ["notes"] = 1,
        ["pages"] = 103,
        ["performance_in_pages"] = {},
        ["series"] = "N/A",
        ["title"] = "The Prophet",
    },
    ["summary"] = {
        ["modified"] = "2023-12-20",
        ["status"] = "reading",
    },
    ["text_lang"] = "en-US",
    ["text_lang_embedded_langs"] = true,
    ["toc_ticks_ignored_levels"] = {},
}
